# Generated by Django 2.1.2 on 2018-10-23 12:42

import auctionApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=200)),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=100)),
                ('d_version', models.IntegerField(default=0)),
                ('bid_version', models.IntegerField(default=0)),
                ('previous_bid', models.DecimalField(decimal_places=2, default=0.01, max_digits=100)),
                ('bid_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=auctionApp.models.get_deadline)),
                ('active', models.BooleanField(default=True)),
                ('banned', models.BooleanField(default=False)),
                ('due', models.BooleanField(default=False)),
                ('adjucated', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('current_winning_bidder', models.CharField(blank=True, max_length=120, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctionApp.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0.01, max_digits=100)),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auctionApp.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctionApp.Bid')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together={('title', 'slug')},
        ),
    ]
